name: ServerLogManager
author: alvin0319
main: alvin0319\ServerLogManager\ServerLogManager
version: 1.0.0
api: 3.0.0

permissions:
  logManager:
    default: op
    children:
      logManager.command:
        default: op